mein/urls.py
from django.contrib import admin
from django.urls import path, include
from mein import views
from django.conf.urls.static import static
from django.conf import settings

from mein import views as user_views

urlpatterns = [
                  path('', views.index, name='index'),
                  path('admin/', admin.site.urls),
                  path('login/', views.login_user, name='login'),
                  path('about/', views.about, name='about'),
                  path('test/', views.test, name='test'),
                  path('proects/', views.proects, name='proects'),
                  path('km/', views.km, name='km'),
                  path('kozm/', views.kozm, name='kozm'),
                  path('buy/<int:id_object>/', views.buy, name='buy'),
                  path('pdf', views.getpdf, name='pdf'),
                  path('shedule', views.shedule, name='shedule'),
                  path('send_mail/', views.send_email, name="send_mail"),
                path('logout/', views.logout_user, name='logout'),
                path('most1/', views.most1, name='most1'),

    # path('auth/', include('authentification.urls')),
                  #
                  # path('<pk>/pdf', views.users_render_pdf_view, name='user_pdf_view'),
              ]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mein/forms.py
from django import forms
from django.contrib.auth.models import User

# sendemail/forms.py
from django import forms


class ContactForm(forms.Form):
    email = forms.EmailField(label='Email', required=True)
    subject = forms.CharField(label='Тема', required=True)
    message = forms.CharField(label='Сообщение', widget=forms.Textarea, required=True)


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get('username')
        password = cleaned_data.get('password')

        try:
            self.user = User.objects.get(username=username)
        except User.DoesNotExist:
            raise forms.ValidationError(f'Пользователь с логином "{username}" не найден !')

        if not self.user.check_password(password):
            raise forms.ValidationError(f'Пароль для пользователя "{username}" не верный !')

        return cleaned_data


class RegisterForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].required = True
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form_input'

    class Meta:
        model = User
        fields = ('username', 'email', 'password')
        widgets = {
            'password': forms.PasswordInput()
        }

templates/about-us.html
{% extends 'base-page.html' %}
{% load static %}

{% block title %}
    О нас
{% endblock title %}

{% block container %}


<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title> Main</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'bootstrap_icons/css/bootstrap_icons.css' %}">

</head>

<body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
<div class="container marketing">
<h1>О нас</h1>
    <h2>МИССИЯ <br>
ЦЕННОСТИ<br>
СТРАТЕГИЯ<br>
</h2>
    <h3>Мы создаем современную и безопасную
инфраструктуру для комфортной жизни людей
и экономического развития регионов в любой точке мира</h3>

   <!-- START THE FEATURETTES -->

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading fw-normal lh-1">ЛИДЕРСТВО – ОТРАСЛЕВОЕ,
РЕГИОНАЛЬНОЕ, НАЦИОНАЛЬНОЕ.
ВЫХОД НА МЕЖДУНАРОДНЫЕ РЫНКИ </h2>
        <p class="lead">Сейчас мы – лидеры строительного рынка Москвы и одни из лидеров на рынке России. Мы стабильная, перспективная и постоянно растущая компания – флагман строительной отрасли, лидер внедрения инноваций в управление и производственные процессы.
            <br>
            Мы обеспечиваем высокое качество в реализации самых сложных проектов и выходим на новые международные рынки – СНГ и мира, претендуем на занятие лидирующих позиций на этих рынках в ближайшем будущем.
        </p>
      </div>
      <div class="col-md-5">
          <img src="{% static 'images/7.jpg' %}" class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500">
             </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7 order-md-2">
        <h2 class="featurette-heading fw-normal lh-1">МЕНЯЕМ СТАНДАРТЫ ВОЗМОЖНОГО </h2>
        <p class="lead">Мы созданы для решения самых сложных задач градостроительного развития. Мы опираемся на опыт десятилетий, приветствуем
            инновации и добиваемся поставленных целей. Мы развиваем сеть московского метро
            и реализуем крупнейшие дорожные и гражданские объекты.</p>
      </div>
      <div class="col-md-5 order-md-1">
        <img src="{% static 'images/9.jpg' %}" class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500">  </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading fw-normal lh-1">СОЗДАЕМ ТЕРРИТОРИЮ КОМФОРТА.
ПРОЕКТЫ ДЛЯ ЛЮДЕЙ.
ПРОСТРАНСТВА ДЛЯ ЖИЗНИ</h2>
        <p class="lead">Мы – лидеры в сфере проектирования и строительства комфортной, экологичной и благоприятной для человека городской среды
            <br>
            Наши решения позволяют людям получать максимальное удовольствие от жизни в мегаполисе – быстро и безопасно перемещаться по городу, открывать
            для себя новые локации на карте города, активно проводить свой досуг.
            <br>
            Мы формируем новые эталоны качества жизни, комфорта, безопасности.
        </p>
      </div>
      <div class="col-md-5">
        <img src="{% static 'images/8.jpg' %}" class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500">  </div>
    </div>

    <hr class="featurette-divider">

    <!-- /END THE FEATURETTES -->

</div>
</body>
{% endblock container %}

templates/base-page.html
{% load static %}
{% load bootstrap_icons %}
<!doctype html>
<html class="no-js" lang="zxx">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <link href="/docs/5.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/product.css' %}">

    <title>{% block title %}Main{% endblock title %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

</head>

<body>

<header style="height: 90px;" class="site-header sticky-top py-1 d-flex flex-wrap align-items-center justify-content-center justify-content-md-between <!--py-3--> border-bottom">
  <div class="col-md-3 mb-2 mb-md-0">
    <a href="/" class="d-inline-flex link-body-emphasis text-decoration-none">
      <svg class="bi" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
    </a>
  </div>

  <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
    <li><a href="/" class="nav-link px-2 text-white">Главная</a></li>
    <li><a href="{% url 'proects' %}" class="nav-link px-2 text-white">Проекты</a></li>

        <li><a href="{% url 'about' %}" class="nav-link px-2 text-white">О нас</a></li>

    <li><a href="#" class="nav-link px-2 text-white">Контакты</a></li>

       {% if user.is_authenticated  %}

            <li><a href="{% url 'test' %}" class="nav-link px-2 text-white">Мосты</a></li>
            <li><a href="{% url 'shedule' %}" class="nav-link px-2 text-white">Графики</a></li>
             <p  class="nav-link px-2 text-white" style="color: white">  {{ user.username }}  </p>
                <a class="nav-link px-2 text-white" href="{% url 'logout' %}">
                    Выйти</a>

        {% else %}
          <a  href="{% url 'login' %}" class="btn btn-outline-primary me-2 login" style="height: 40px;"> Войти </a>
           <!-- <button type="button" class="btn btn-primary"><a class="btn-primary" href=""> Регистрация </a></button>-->
        {% endif %}
  </ul>

  <div class="col-md-3 text-end">

  </div>
</header>



{% block container %}

{% endblock container %}

<div class="container">
  <footer class="py-5">
    <div class="row">
      <div class="col-6 col-md-2 mb-3">
        <h5>Информация</h5>
        <ul class="nav flex-column">
          <li class="nav-item mb-2"><a href="{% url 'about' %}" class="nav-link p-0 text-body-secondary">О нас</a></li>
          <li class="nav-item mb-2"><a href="{% url 'test' %}" class="nav-link p-0 text-body-secondary">Услуги</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Условия и положения</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Политика конфидециальности</a></li>
        </ul>
      </div>

      <div class="col-6 col-md-2 mb-3">
        <h5>Cлужба поддержки клиентов</h5>
        <ul class="nav flex-column">
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Наши контакты</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">FAQs</a></li>
        </ul>
      </div>

      <div class="col-6 col-md-2 mb-3">
        <h5>Есть вопросы ?</h5>
        <ul class="nav flex-column">
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">most@gmail.com</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">8-800-555-35-35</a></li>

        </ul>
      </div>

     <!-- <div class="col-md-5 offset-md-1 mb-3">
        <form>

          <h5>Оставьте заявку на консультацию</h5>
          <p>Мы перезвоним вам</p>
          <div class="d-flex flex-column flex-sm-row w-100 gap-3">
            <label for="newsletter1" class="visually-hidden">Номер телефона </label>
            <input id="newsletter1" type="text" class="form-control" placeholder="Номер телефона">
            <button class="btn btn-primary" type="button">Жду звонка</button>
          </div>
        </form>
      </div>-->
    </div>

    <div class="d-flex flex-column flex-sm-row justify-content-between py-4 my-4 border-top">
      <p>© 2023 Company, Inc. All rights reserved.</p>
      <ul class="list-unstyled d-flex">
        <li class="ms-3"><a class="link-body-emphasis" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"></use></svg></a></li>

        <li class="ms-3"><a class="link-body-emphasis" href="#"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-twitter" viewBox="0 0 16 16">
  <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/>
</svg></a></li>
        <li class="ms-3"><a class="link-body-emphasis" href="#"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-facebook" viewBox="0 0 16 16">
  <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/>
</svg>
        </a></li>
      </ul>
    </div>
  </footer>
</div>

</body>

</html>

templates/buy.html
{% extends 'base-page.html' %}
{% load bootstrap_icons %}

{% load static %}

{% block title %}
    Buy Page
{% endblock title %}

{% block container %}

<head>
    <meta charset="utf-8" />
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'bootstrap_icons/css/bootstrap_icons.css' %}">

</head>



<body >
<div class="container">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
<form method="POST">
        {% csrf_token %}


          <p>  {{ obj.name_object }} </p>
          <p>  {{ obj.id_object }} </p>
            <p>{{ obj.id_classification }}</p>
            <p>{{ obj.id_address }}</p>
            <p>{{ obj.id_status }}</p>
            <p>{{ obj.description }}</p>

                    <img src="{{ obj.photo.url }}" alt="продукт">


    <a href="{% url 'pdf' %}" target="_blank"><button class="btn btn-primary">Download pdf</button></a>

    </form>
</div>

</body>



{% endblock container %}

templates/email.html
{% extends 'base-page.html' %}
{% load bootstrap_icons %}

{% load static %}

{% block title %}
    Mail
{% endblock title %}

{% block container %}

<head >
    <meta charset="utf-8" />
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'bootstrap_icons/css/bootstrap_icons.css' %}">

</head>



<body class="">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>

</body>
<div class="container">

<form method="POST" action=".">
    {% csrf_token %}
    <div class="col-md-5 col-lg-4 order-md-last">
         <input type="hidden" name="csrfmiddlewaretoken" value="K5fZsQsCxL3ajAPyAV7SftFGkwzLZicDQfDu6685svg39DRvG0XuTvxsOUnJtao4">
    <div class="d-flex flex-column flex-sm-row w-100 gap-3">
         <p>
             <label for="id_email">Email:</label>
             <input type="email" name="email" class="form-control" required="" id="id_email">
         </p>
    </div>
    <div class="d-flex flex-column flex-sm-row w-100 gap-3">
        <p>
         <label for="id_subject">Тема:</label>
        <input type="text" name="subject" required="" class="form-control"  id="id_subject">
        </p>
    </div>

    <div class="d-flex flex-column flex-sm-row w-100 gap-3">
         <p>
        <label for="id_message">Сообщение:</label>
        <textarea name="message"  class="form-control"  cols="40" rows="10" required="" id="id_message"></textarea>
        </p>
    </div>
<button class="btn btn-primary">Отправить</button>
    </div>
</form>

</div>

{% endblock container %}

templates/index.html
{% extends 'base-page.html' %}
{% load bootstrap_icons %}

{% load static %}

{% block title %}
    Главная
{% endblock title %}

{% block container %}

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title> Main</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'bootstrap_icons/css/bootstrap_icons.css' %}">
 <!--   &lt;!&ndash; <link rel="manifest" href="site.webmanifest"> &ndash;&gt;
    <link rel="shortcut icon" type="image/x-icon" href="{% static '/images/img/favicon.png'  %}">
    &lt;!&ndash; Place favicon.ico in the root directory &ndash;&gt;

    &lt;!&ndash; CSS here &ndash;&gt;
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'  %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css'  %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css'  %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css'  %}">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css'  %}">
    <link rel="stylesheet" href="{% static 'css/gijgo.css'  %}">
    <link rel="stylesheet" href="{% static 'css/nice-select.css'  %}">
    <link rel="stylesheet" href="{% static 'css/flaticon.css'  %}">
    <link rel="stylesheet" href="{% static 'css/slicknav.css'  %}">

    <link rel="stylesheet" href="{% static 'css/style.css'  %}">-->
    <!-- <link rel="stylesheet" href="css/responsive.css"> -->
</head>

<body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  <div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
          <img src="{% static 'images/2.jpg' %}" class="bd-placeholder-img" width="100%" height="100%">
    <!--    <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false">
            <rect width="100%" height="100%" fill="var(&#45;&#45;bs-secondary-color)"/>
        </svg>-->
        <div class="container">
          <div class="carousel-caption text-start">
            <h1>Ремонт и реконструкция инженерных сооружений</h1>
            <p>РЕМОНТ И РЕКОНСТРУКЦИЯ ИНЖЕНЕРНЫХ СООРУЖЕНИЙ ПОД КЛЮЧ C ГАРАНТИЕЙ 3 ГОДА</p>
            <p><a class="btn btn-lg btn-primary" href="#">Подробнее</a></p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
           <img src="{% static 'images/3.jpg' %}" class="bd-placeholder-img" width="100%" height="100%">

       <div class="container">
          <div class="carousel-caption">
            <h1>Ремонт и реконструкция инженерных сооружений</h1>
            <p>РЕМОНТ И РЕКОНСТРУКЦИЯ ИНЖЕНЕРНЫХ СООРУЖЕНИЙ ПОД КЛЮЧ C ГАРАНТИЕЙ 3 ГОДА</p>
            <p><a class="btn btn-lg btn-primary" href="#">Подробнее</a></p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
       <img src="{% static 'images/4.jpg' %}" class="bd-placeholder-img" width="100%" height="100%">
          <div class="container">
          <div class="carousel-caption text-end">
            <h1>Ремонт и реконструкция инженерных сооружений</h1>
            <p>РЕМОНТ И РЕКОНСТРУКЦИЯ ИНЖЕНЕРНЫХ СООРУЖЕНИЙ ПОД КЛЮЧ C ГАРАНТИЕЙ 3 ГОДА</p>
            <p><a class="btn btn-lg btn-primary" href="#">Подробнее</a></p>
          </div>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>


  <!-- Marketing messaging and featurettes
  ================================================== -->
  <!-- Wrap the rest of the page in another container to center all the content. -->


<div class="container marketing">

    <!-- Three columns of text below the carousel -->
    <div class="row">


      <div class="col-lg-4">
         <h2 class="fw-normal">КОНТРОЛЬ КАЧЕСТВА В СТРОИТЕЛЬСТВЕ</h2>
        <p>Компания “Prometheus” осуществляет сквозной комплексный контроль качества от производства оборудования и материалов для рПланирования работ по эксплуатации и ремонту транспортных инженерных сооружений </p>
      </div><!-- /.col-lg-4 -->
      <div class="col-lg-4">

         <h2 class="fw-normal">ИННОВАЦИОННЫЕ МЕТОДИКИ КОНТРОЛЯ</h2>
        <p>Компания “Prometheus” применяет распределенные мобильные решения для осуществления строительного контроля.
            В единое информационное поле качества строительно-монтажных работ вовлечены все участники строительства.</p>
      </div><!-- /.col-lg-4 -->
      <div class="col-lg-4">
        <h2 class="fw-normal">КВАЛИФИКАЦИЯ ПЕРСОНАЛА</h2>
        <p>Компания “Prometheus” сотрудничает только с квалифицированными бригадами с опытом работ более 15-ти лет.</p>
      </div><!-- /.col-lg-4 -->
    </div><!-- /.row -->


    <!-- START THE FEATURETTES -->

    <!-- /END THE FEATURETTES -->

  </div>
<main>

<div class="container col-xxl-8 px-4 py-5">
    <div class="row flex-lg-row-reverse align-items-center g-5 py-5">
      <div class="col-10 col-sm-8 col-lg-6">
        <img src="{%static 'images/1.webp' %}" class="d-block mx-lg-auto img-fluid" alt="Bootstrap Themes" width="900" height="700" loading="lazy">
      </div>
      <div class="col-lg-6">
        <h1 class="display-5 fw-bold text-body-emphasis lh-1 mb-3">ПРОИЗВОДСТВЕННАЯ БЕЗОПАСНОСТЬ</h1>
        <p class="lead">Стратегия холдинга в области производственной безопасности направлена на достижение цели «Ноль несчастных случаев
          : отсутствие вреда людям, окружающей среде и имуществу при выполнении работ.
          <br>
          Жизнь и здоровье сотрудников и подрядчиков – ключевой приоритет компании. Каждый, кто работает в
       или вместе с «Мосинжпроект», играет важную роль в обеспечении безопасности труда.
        </p>
      </div>
    </div>
  </div>
  <div class="container col-xxl-8 px-4 py-5">
    <div class="row flex-lg-row-reverse align-items-center g-5 py-5">
         <div class="col-lg-6">
        <h1 class="display-5 fw-bold text-body-emphasis lh-1 mb-3">РЕЗУЛЬТАТЫ СПЕЦИАЛЬНОЙ ОЦЕНКИ УСЛОВИЙ ТРУДА</h1>
        <p class="lead">
        </p>
      </div>
      <div class="col-10 col-sm-8 col-lg-6">
        <img src="{%static 'images/12.jpg' %}" class="d-block mx-lg-auto img-fluid" alt="Bootstrap Themes" width="900" height="700" loading="lazy">
      </div>

    </div>
  </div>
  <div class="container col-xxl-8 px-4 py-5">
    <div class="row flex-lg-row-reverse align-items-center g-5 py-5">
      <div class="col-10 col-sm-8 col-lg-6">
        <img src="{%static 'images/10.jpg' %}" class="d-block mx-lg-auto img-fluid" alt="Bootstrap Themes" width="900" height="700" loading="lazy">
      </div>
      <div class="col-lg-6">
        <h1 class="display-5 fw-bold text-body-emphasis lh-1 mb-3">ТЕХНОЛОГИЧЕСКАЯ БЕЗОПАСНОСТЬ</h1>
        <p class="lead">
        </p>
      </div>
    </div>
  </div>
  <div class="container col-xxl-8 px-4 py-5">
    <div class="row flex-lg-row-reverse align-items-center g-5 py-5">

      <div class="col-lg-6">
        <h1 class="display-5 fw-bold text-body-emphasis lh-1 mb-3">ОХРАНА ТРУДА И ЗДОРОВЬЯ</h1>
        <p class="lead">
        </p>
      </div>
      <div class="col-10 col-sm-8 col-lg-6">
        <img src="{%static 'images/11.jpg' %}" class="d-block mx-lg-auto img-fluid" alt="Bootstrap Themes" width="900" height="700" loading="lazy">
      </div>
    </div>
  </div>

</main>
{% endblock container %}

templates/pdf.html
<body> 
<form method="POST" class="post-form" enctype="multipart/form-data"> 
{% csrf_token %} 
{{ form.as_p }} 
<button type="submit" class="save btn btn-default">Save</button> 
</form> 
</body>